### DISCUSSION TITLE
(solved) can't get the dark mode working

### DISCUSSION THREAD

**Discussion by berkas1** [luizdepra/hugo-coder#805] [General]
Hi, I have a problem with the dark mode - the toggle button does nothing (light theme stays on). It changes the `<html>` and `<body>` tag, nothing in javascript console. Defining `colorScheme: dark` in config file also does not help, tested in Firefox and Chrome (recent version). This happens for both local and deployed site. The command for local site I use is `hugo serve --config dev-config.yaml --bind 0.0.0.0`.

I use hugo v0.111.3. Does anyone have some idea what am I doing wrong? My config file follows:

```
---

baseURL: 'http://localhost:1313'
languageCode: 'en'
theme: "hugo-coder"
title: "xz"


markup:
  markup.highlight:
    style: "onesenterprise"


menu:
  main:
  - name: "Articles"
    weight: 10
    url: "/posts"


taxonomies:
  category: "categories"
  series: "series"
  tag: "tags"

```
