### ISSUE TITLE
[Help wanted] The date error in posts

### ISSUE THREAD

**Issue by kobeHub** [luizdepra/hugo-coder#136]
# Date error in the posts and posts list

Very thank you for making such a great theme. I was confused by the date problem in the posts for few days. The "2019-01-08" will be presented as "8019-01-08", and "2019-01-03" as "3019-01-03". 

## The config file
```toml
baseurl = "https://kobehub.github.io"
title = "Innohub"

theme = "hugo-coder"

languagecode = "zh-CN"

enableemoji = true
paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "Inno"

[params]
    author = "Inno Jia"
    description = "Inno Jia's personal website"
    keywords = "blog,developer,personal"
    info = "Machine learning and algorithm"
    avatarurl = "images/avatar.jpg"
    footercontent = "It's not a bug, it's future"

    dateformat = "January 2, 2019"

    hideCredits = false
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Use inverted colors
    inverted = false

    # Custom CSS
    custom_css = []

[frontmatter]
date = ["2019-01-08", ":default"]

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/kobeHub/"
[[params.social]]
    name = "Kaggle"
    icon = "fab fa-kaggle"
    weight = 2
    url = "https://www.kaggle.com/Innojia/"
[[params.social]]
    name = "leetcode"
    icon = "fas fa-code"
    weight = 3
    url = "https://leetcode.com/innobit/"
[[params.social]]
    name = "stackoverflow"
    icon = "fab fa-stack-overflow"
    weight = 4
    url = "https://stackoverflow.com/users/10722224/inno-jia"
[[params.social]]
    name = "Gmail"
    icon = "fab fa-google-plus"
    weight = 5
    url = "mailto:jdgets111@gmail.com"


[languages]
    [languages.en]
        languagename = "en" # The language name to be diszh-CNayed in the selector.
        title = "Inno Jia"

        # You can configure the theme parameter for each language.
        [languages.en.params]
        author = "Inno Jia"
        info = "Machine learning and algorithm"
        description = "Inno Jia's personal website"
        keywords = "blog,developer,personal"

        [languages.en.menu] # It is possible to change the menu too.

        [[languages.en.menu.main]]
        name = "About"
        weight = 1
        url = "/about/"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 2
        url = "/posts/"

        [[languages.en.menu.main]]
        name = "Projects"
        weight = 3
        url = "/projects/"

        [[languages.en.menu.main]]
        name = "Contact me"
        weight = 5
        url = "/contact/"


    [languages.zh-CN]
        languagename = "zh-CN"
        title = "贾栋"

        [languages.zh-CN.params]
            author = "贾栋"
            description = "代码是连接硅基生命和碳基生命的一个桥梁"
            keywords = "博客, 技术分享, 随笔"
            info = "机器学习，深度学习，算法"

        [languages.zh-CN.menu]

            [[languages.zh-CN.menu.main]]
            name = "关于"
            weight = 1
            url = "/zh-cn/about/"

            [[languages.zh-CN.menu.main]]
            name = "文章"
            weight = 2
            url = "/posts/"

            [[languages.zh-CN.menu.main]]
            name = "项目"
            weight = 3
            url = "/projects/"

            [[languages.zh-CN.menu.main]]
            name = "联系我"
            weight = 5
            url = "/zh-cn/contact/"
```
## The posts header 
```
+++
draft = false
date = 2019-01-08T10:10:02+08:00
title = "Record of build GitHub Pages use pages"
slug = "record-of-build-github-pages-use-hugo" 
tags = ["Hugo", "tutorial"]
categories = ["Record"]
+++
```
My site is [kobeHub.github.io](https://kobeHub.github.io/posts). I don't know what is going wrong and how to fix it.
