### ISSUE TITLE
Mixed content in netlify builds

### ISSUE THREAD

**Issue by SerhatTeker** [luizdepra/hugo-coder#249]
Hi there,

I'm getting `mixed content detected` warnings in netlify builds. Although my `baseurl` is not `http://www.example.com`. Part of them can be found below.

```
4:32:06 PM: Mixed content detected in: /categories/golang/index.html
4:32:06 PM: --> insecure link urls:
4:32:06 PM:   - http://www.example.com/categories/golang/
4:32:06 PM:   - http://www.example.com/css/coder.min.cd087ace86754b082dec94545567f8361cba42e84f8e15edbc4a9f6e52bd1f6a.css
4:32:06 PM:   - http://www.example.com/images/favicon-32x32.png
4:32:06 PM:   - http://www.example.com/images/favicon-16x16.png
4:32:06 PM:   - http://www.example.com/categories/golang/index.xml
4:32:07 PM: Mixed content detected in: /categories/golang/page/1/index.html
4:32:07 PM: --> insecure link urls:
4:32:07 PM:   - http://www.example.com/categories/golang/
4:32:13 PM: Mixed content detected in: /pl/404.html
4:32:13 PM: --> insecure link urls:
4:32:13 PM:   - http://www.example.com/css/coder.min.cd087ace86754b082dec94545567f8361cba42e84f8e15edbc4a9f6e52bd1f6a.css
4:32:13 PM:   - http://www.example.com/images/favicon-32x32.png
4:32:13 PM:   - http://www.example.com/images/favicon-16x16.png
4:32:27 PM: Mixed content detected in: /tr/tags/page/1/index.html
4:32:27 PM: --> insecure link urls:
4:32:27 PM:   - http://www.example.com/tr/tags/
```

How can we resolve this issue?

For some other examples: https://github.com/gohugoio/hugoThemes/issues/532#issuecomment-455900414

**Comment by luizdepra** [comment]
I think you only need to change your URL to an HTTPS one.

**Comment by SerhatTeker** [comment]
Mine is already HTTPS :) `https://serhatteker.com`

I don't understand why "www.example.com"s are in my builds? In my public folders. Since this url is only in `themes/exampleSite`. Not in my repo.

**Comment by luizdepra** [comment]
There is any repository or configuration file (hugo and netlify) that I could take a look?

**Comment by SerhatTeker** [comment]
Sure you can find the config files below. Sorry for long content, they are not os.

In addition, I don't think it is related only netlify since in local build, public folders, there are **www.example.com** in `meta datas` and `ref links`.


`config.toml`

```toml
baseurl = "https://serhatteker.com"
title = "serhatteker"

theme = "hugo-coder"

languagecode = "en-us"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# disqus
disqusShortname = ""
# analytics
googleAnalytics = ""

[params]
    author = "Serhat Teker"
    description = "Serhat Teker's personal website"
    keywords = "keywords"
    info = "Info"

    avatarurl = "images/avatar.jpg"
    favicon_32 = "images/favicon-32x32.png"
    favicon_16 = "images/favicon-16x16.png"

    dateformat = "January 2, 2006"
    projectdateformat = "January 2006"

    footercontent = "Some content"

    hideCredits = true
    hideCopyright = false

    rtl = false

    # Use inverted colors
    inverted = false

    math = true

    # Custom CSS
    custom_css = []


[[params.social]]
    name = "Mail"
    icon = "fas fa-envelope"
    weight = 1
    url = "mailto:serhat.teker@gmail.com"
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 2
    url = "https://github.com/SerhatTeker/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/SerhatTeker/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/serhat-teker-6a715b39/"
[[params.social]]
    name = "Dev.to"
    icon = "fab fa-dev"
    weight = 5
    url = "https://dev.to/serhatteker"


[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = "Blog"
    weight = 2
    url  = "/posts/"
[[menu.main]]
    name = "Projects"
    weight = 3
    url = "/projects/"
[[menu.main]]
    name = "Tech Blog"
    weight = 4
    url  = "https://tech.serhatteker.com/"


[languages]
    [languages.en]
        languagename = "English" # The language name to be displayed in the selector.
        title = "Serhat Teker"

        # You can configure the theme parameter for each language.
        [languages.en.params]
        author = "Serhat Teker"
        info = "Uomo Universale"
        description = "Serhat Teker's personal website"
        keywords = "keywords"

        [languages.en.menu] # It is possible to change the menu too.

        [[languages.en.menu.main]]
        name = "About"
        weight = 1
        url = "/about/"
        [[languages.en.menu.main]]
        name = "Blog"
        weight = 2
        url = "/posts/"
        [[languages.en.menu.main]]
        name = "Projects"
        weight = 3
        url = "/projects/"
        [[languages.en.menu.main]]
        name = "Tech Blog"
        weight = 4
        url  = "https://tech.serhatteker.com/"


    [languages.de]
        languagename = "Deutsch"
        title = "Serhat Teker"

        [languages.de.params]
            author = "Serhat Teker"
            info = "Uomo Universale"
            description = "Serhat Tekers persönliche Website"
            keywords = "keywords"

        [languages.de.menu]

            [[languages.de.menu.main]]
            name = "Über"
            weight = 1
            url = "/de/about/"
            [[languages.de.menu.main]]
            name = "Blog"
            weight = 2
            url = "/de/posts/"
            [[languages.de.menu.main]]
            name = "Projekte"
            weight = 3
            url = "/de/projects/"
            [[languages.de.menu.main]]
            name = "Tech Blog"
            weight = 4
            url = "https://tech.serhatteker.com/"
```

`netlify.toml`

```toml
[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.54.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo  --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.54.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo  --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.54.0"

[context.branch-deploy]
command = "hugo  --gc --minify"

[context.branch-deploy.environment]
HUGO_VERSION = "0.54.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

# Specific branch context: all deploys from this specific branch will inherit
# these settings.
[context.tech] # 'staging' is a branch name
command = "hugo --gc --minify"
base = "tech"

[context.tech.environment]
HUGO_ENV = "tech"
HUGO_VERSION = "0.54.0"
HUGO_ENABLEGITINFO = "true"
```
