### ISSUE TITLE
Add support for Fathom Analytics

### ISSUE THREAD

**Issue by yashmehrotra** [luizdepra/hugo-coder#263]
Fathom Analytics is a simpler and more privacy-focused alternative to Google Analytics. They are open source as well (https://github.com/usefathom/fathom)

I have tweaked this theme on my local setup and have got a working model for this. All an end user would have to do is the following lines in `config.toml`

```toml
[params.fathomAnalytics]
    siteID = "ABCDE"
    rootURL = "analytics.example.com"
```

If you are interested in such a feature, I'd be happy to create a PR for the same.
