### ISSUE TITLE
Footer doesn't display author name

### ISSUE THREAD

**Issue by endormi** [luizdepra/hugo-coder#339]
![footer](https://user-images.githubusercontent.com/39559256/82728736-0d2d0500-9cfb-11ea-899e-52f268d3ddd6.PNG)

Footer doesn't show my author name (seems in other repositories that it shows author name after copyright).

My `config.toml`:

```toml
[params]
    author = "my name"
    info = "some info" 
    description = "Endormi's personal website"
    keywords = "developer,personal,website,portfolio"
    avatarurl = "images/avi.png"
    favicon_32 = "images/avi.png"
    favicon_16 = "images/avi.png"
    hidecredits = true
    rtl = false
    custom_css = ["/css/custom.css"]
```
