### ISSUE TITLE
Read time does not work for RU lang

### ISSUE THREAD

**Issue by PakhomovAlexander** [luizdepra/hugo-coder#362]
When the article comes bigger than 1-minute read for the Russian language I get this 
<img width="162" alt="image" src="https://user-images.githubusercontent.com/20556627/86918496-7ba11780-c12f-11ea-843e-d5964e10c7b5.png">

But if I change i18n/ru.toml from :
```toml
[reading_time]
one = "Читать одну минуту"
other = "Читать около {{ .Count }} минут"
```

to 

```toml
[reading_time]
other = "Читать около {{ .Count }} минут"
```

I get it right 
<img width="250" alt="image" src="https://user-images.githubusercontent.com/20556627/86918700-b7d47800-c12f-11ea-8ae6-a0549b98f70e.png">

I think there is such a problem for all languages that have `one` and `other ` keys at the same time. English does not :)
