### ISSUE TITLE
Overlapping of tags in project archetype branch

### ISSUE THREAD

**Issue by iamrajiv** [luizdepra/hugo-coder#408]
I have used `add-project-archetype` branch and also updated the tags style and made it like this
<img width="84" alt="Screenshot 2020-09-21 at 9 52 54 AM" src="https://user-images.githubusercontent.com/42106787/93732751-4b2a2f00-fbf0-11ea-9065-b7e0d4448fe7.png">
But when I used lot of tags it gets overlapped something like this
<img width="363" alt="Screenshot 2020-09-21 at 9 43 46 AM" src="https://user-images.githubusercontent.com/42106787/93732763-6137ef80-fbf0-11ea-96b9-ccdc116f610b.png">
For tags style, I have made a new layout in `layouts/partials/taxonomy` called `technologies.html`
Code used in  ``technologies.html` are
```html
{{ range $index, $el := . }}
  <a class="card-tag {{ trim (lower .) "!/" }}" style="text-decoration:none">{{ . }}</a>
{{ end }}
```
I have also updated `_card.scss` by adding this
```scss
.card-tag {
  padding: 0.5rem 1rem;
  margin-right: 0.5rem;

  font-size: smaller;
  text-align: center;
  color: $bg-color;
  background-color: $link-color;

  border-radius: 0.5rem;
}
```

**Comment by luizdepra** [comment]
Have you tried to play with different `line-height` values?

I must say that the project archetype branch will suffer tons of modifications and it may not be compatible with it the current state.

**Comment by clement-pannetier** [comment]
@iamrajiv Did you manage to fix your issue ?

**Comment by iamrajiv** [comment]
Thank You @luizdepra @clement-pannetier I have resolved the issue.
<img width="363" alt="Screenshot 2020-10-19 at 11 15 59 PM" src="https://user-images.githubusercontent.com/42106787/96492449-472a1500-1261-11eb-9228-3c7d9ea2dff6.png">

I have added this code snippets in `_card.scss`
```scss
.card-tags {
  padding: 1.5rem 2rem;
  line-height: 3.2rem;
}
```
But I am not sure how much `line-height` we have to give. It will look good if it has the same space what we have in between the tags.
