### ISSUE TITLE
URL with a Trailing Slash is not rendering pages properly.

### ISSUE THREAD

**Issue by CrazyOptimist** [luizdepra/hugo-coder#410]
![https://crazyoptimist.net/letsencrypt/](https://user-images.githubusercontent.com/55074937/94218718-a5561900-feaa-11ea-8c0b-2d214a8c41ce.png)
![https://crazyoptimist.net/letsencrypt](https://user-images.githubusercontent.com/55074937/94218725-ab4bfa00-feaa-11ea-84de-1576d2d80137.png)
Is this an issue from hugo or from this theme? Not sure ...

**Comment by luizdepra** [comment]
I think it is something relative to your configuration.

See these examples:
- https://hugo-coder.netlify.app/huebr/
- https://hugo-coder.netlify.app/huebr

Both are working fine.
Mind sharing your `config.toml`?

**Comment by CrazyOptimist** [comment]
Thanks for reply, here it is.
```toml
#baseurl = "https://crazyoptimist.net"
relativeURLs = true
title = "Crazy Optimist"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "crazy-optimist"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
    author = "Crazy Optimist"
    info = "Crazy Optimist and Software Engineer"
    description = "A crazy simple stupid thing separates the doers from the dreamers."
    keywords = "crazyoptimist,optimist,optimistic,optimism,crazy"
    avatarurl = "images/avatar.svg"

    favicon_32 = "/favicon-32x32.png"
    favicon_16 = "/favicon-16x16.png"
    touchicon = "/apple-touch-icon.png"

    footercontent = ""

    hidecredits = true
    hidecopyright = false

    rtl = false
    math = false
    custom_css = []
    custom_js = []
    
    colorscheme = "auto"
    enableTwemoji = true

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/CrazyOptimist/"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-gitlab fa-2x"
    weight = 2
    url = "https://gitlab.com/dockerlead/"
[[params.social]]
    name = "Email"
    icon = "fas fa-envelope-open-text fa-2x"
    weight = 3
    url = "mailto:hey@crazyoptimist.net"
[[params.social]]
    name = "DEV"
    icon = "fab fa-dev fa-2x"
    weight = 4
    url = "https://dev.to/crazyoptimist"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium fa-2x"
    weight = 5
    url = "https://medium.com/@crazyoptimist"
#[[params.social]]
#    name = "RSS"
#    icon = "fas fa-rss fa-2x"
#    weight = 6
#    url = "/index.xml"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about"
```

**Comment by luizdepra** [comment]
I suspect that `relativeURLs` and `canonifyurls` are conflicting. If you want to use relative URLs, try removing `canonifyurls` or setting it to `false`.

**Comment by CrazyOptimist** [comment]
hmmm, tried it but still same issue with these settings:
```toml
relativeurls = true
canonifyurls = false
```
weird..
