### ISSUE TITLE
[v2] Flags on Language Labels

### ISSUE THREAD

**Issue by luizdepra** [luizdepra/hugo-coder#419]
Check if we can use flags as language labels. Probably we'll need to use Twemoji together.

**Comment by clement-pannetier** [comment]
@luizdepra It's already working with twemoji as you can see below:

![image](https://user-images.githubusercontent.com/35581688/96377266-f93fdf00-1184-11eb-93fd-65827f43981a.png)

Config:
```toml
enableTwemoji = true

[languages.en]
            languagename = "🏴󠁧󠁢󠁥󠁮󠁧󠁿"
            ...
[languages.pt-br]
            languagename = "🇧🇷"
            ...
[languages.fr]
            languagename = "🇫🇷"
            ...
```
List of emoji flags: https://emojipedia.org/flags/
