### ISSUE TITLE
Phone social button with tel:

### ISSUE THREAD

**Issue by g0rbe** [luizdepra/hugo-coder#422]
I tried to set up a phone number social button:

``` toml
[[languages.hu.params.social]]
            name = "Mobil"
            icon = "fas fa-phone"
            weight = 1
            url = "tel:+3611111111"
```

I thought url will be placed in `href=""`, but i get the following result:

``` html
 <li>
     <a href="#ZgotmplZ" aria-label="Phone"   >
         <i class="fas fa-phone" aria-hidden="true"></i>
     </a>
</li>
```

**Expected result:**

``` html
 <li>
     <a href="tel:+3611111111" aria-label="Phone"   >
         <i class="fas fa-phone" aria-hidden="true"></i>
     </a>
</li>
```

How can i add phone number social button? I trying to set up to be able to call with one push.

Thanks,
    g0rbe

Edit:

`mailto:` seems to working.
