### ISSUE TITLE
The Social Icons Broken

### ISSUE THREAD

**Issue by jtr109** [luizdepra/hugo-coder#449]
Hi, there.

I updated the theme (with commit 733bc74) and deployed on my site. But I found the social icons are broken on[ my homepage](https://jtr109.github.io/). 

Here is a screenshot below:

![image](https://user-images.githubusercontent.com/13946679/96954674-6f966580-1526-11eb-8945-4ec9aca8fd8d.png)

<details>

<summary>Here is a part of my configurations.</summary>

```toml
[[params.social]]
    name = "GitHub"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/jtr109/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/conbas2019/"
[[params.social]]
    name = "Mail"
    icon = "fas fa-envelope"
    weight = 4
    url = "mailto:conbas2019@gmail.com"
[[params.social]]
    name = "RSS"
    icon = "fas fa-rss"
    weight = 5
    url = "/index.xml"
    rel = "alternate"
    type = "application/rss+xml"
```

</details>

<details>

<summary>I found the HTML generation works well.</summary>

```html
<ul>
      
        
          <li>
            <a href="https://github.com/jtr109/" aria-label="GitHub">
              <i class="fab fa-github fa-2x" aria-hidden="true"></i>
            </a>
          </li>
        
      
        
          <li>
            <a href="https://twitter.com/conbas2019/" aria-label="Twitter">
              <i class="fab fa-twitter fa-2x" aria-hidden="true"></i>
            </a>
          </li>
        
      
        
          <li>
            <a href="mailto:conbas2019@gmail.com" aria-label="Mail">
              <i class="fas fa-envelope" aria-hidden="true"></i>
            </a>
          </li>
        
      
        
          <li>
            <a href="https://jtr109.github.io/index.xml" aria-label="RSS" rel="alternate" type="application/rss+xml">
              <i class="fas fa-rss" aria-hidden="true"></i>
            </a>
          </li>
        
      
    </ul>
```

</details>

I think the [`.css`](https://cdn.jsdelivr.net/npm/fork-awesome@1.1.7/css/fork-awesome.min.css) from [Font Awesome](https://fontawesome.com/) also works well.

Could you please help me to resolve the problem? Hope my informations help.
