### ISSUE TITLE
Social Icons are not rendenring

### ISSUE THREAD

**Issue by underscoreHao** [luizdepra/hugo-coder#604]
Hello, I updated my Coder theme sub-module to latest and my social icons disappeared. I saw #449 but I don't think that's the issue. The icons are not rendered at all as can be seen below

![image](https://user-images.githubusercontent.com/5088351/134805010-b4beedb5-e94a-487f-82d0-19d37620f805.png)

My `config.toml` is using ForkAwesome icon names

```toml
[[params.social]]
icon = "fa fa-github"
name = "Github"
url = "https://github.com/underscoreHao/"
weight = 1
[[params.social]]
icon = "fa fa-stack-overflow"
name = "Stack Overflow"
url = "https://stackoverflow.com/users/2265179/underscorehao"
weight = 2
```

Git Bisect shows me that the icons in my setup started disappearing after this PR - #497
