### ISSUE TITLE
Missing I18n translations for plural taxonomies

### ISSUE THREAD

**Issue by metbril** [luizdepra/hugo-coder#608]
In the partial `terms.html` a reference is made to the plural  taxonomy title ('tags', 'categories'), but that isn't yet available in the translation files.

https://github.com/luizdepra/hugo-coder/blob/6581e860bde43960e3b6362001f270cd2e9db178/layouts/partials/terms.html#L9

An option would be to have the full taxonomy name as the translation key and have values for both `one` and `other`. For example:

**en.toml**

```toml
[tags]
one = "tag"
other = "tags"

[categories]
one = "category"
other = "categories"
```

**nl.toml**

```toml
[tags]
one = "label"
other = "labels"

[categories]
one = "categorie"
other = "categoriën"
```

The terms.html partial and possibly other resources need to be updated to use that new key.
