### ISSUE TITLE
Local font doesn't work

### ISSUE THREAD

**Issue by TingjieGuo** [luizdepra/hugo-coder#740]
I was trying to use a local font for my website. I created a css file at`assets/scss/css/myfont.css` in which I defined the font face with following code:

```css
@font-face {
    font-family: "LXGW Bright";
    font-style: normal;
    font-weight: 400;
    /* font-display: swap; */
    src: url("fonts/LXGWBright-Regular.woff2") format("woff2");
}
```
I then created a `_variables.scss` at `assets/scss/_variables.scss` to override the theme `_variables.scss`. In this scss file I added `@import url("./css/myfont.css");` and added `LXGW Bright` to the `$font-family` and commented out all other fonts pre-defined by hugo-coder theme. The font file is located at `assets/scss/fonts/LXGWBright-Regular.woff2`. 

However, the site doesn't render with the font I defined. I've also tried putting the font files at `static/fonts/LXGWBright-Regular.woff2`. It doesn't work either. I was wondering where I was doing wrong? Many thanks in advance!
