### ISSUE TITLE
On small screens, if there is a horizontal scroll-bar you can csroll far past the text boundary.

### ISSUE THREAD

**Issue by Baa14453** [luizdepra/hugo-coder#821]
## Describe the problem:

On small screens, if there is a horizontal scroll-bar you can csroll far past the text boundary.
This is notable for mobile users.

### Steps to reproduce:

1. View a post in a low width resolution.
2. Scroll horizontally.

### Observed Results:

-  The website will scroll past the text boundary, exactly how far varies but gets worse as the screen gets smaller:
![image](https://github.com/luizdepra/hugo-coder/assets/9057997/377e6968-f5fd-453f-b523-46bce36750f1)

I have added custom SCSS to fix this:
```scss
.content {
    article {
        p {
            text-align: left;
        }
    }
}
```
Would be interested to know of any impacts from this change.
