### ISSUE TITLE
Update wiki with favicon examples

### ISSUE THREAD

**Issue by chipsenkbeil** [luizdepra/hugo-coder#84]
I can't edit the wiki, but I realized that none of the examples include the favicon support added by #81.

```toml
[params]
    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"
```

Also, on the wiki's main page, the Configuration link is invalid. The actual wiki page - as seen on the side menu - is Configurations (plural). As it is now, the Configuration link just takes you back to the main wiki page again.
