### ISSUE TITLE
div overflow when enabled markup.highlight.lineNos and markup.highlight.lineNumbersInTable

### ISSUE THREAD

**Issue by mchu1966** [luizdepra/hugo-coder#917]
## Describe the problem:

When I enabled the `markup.highlight.lineNos` and `markup.highlight.lineNumbersInTable` in hugo.toml, the syntax highlighting code block will overflow when the content is too long that exceed the div width.

### Steps to reproduce:

1. enable `markup.highlight.lineNos` and `markup.highlight.lineNumbersInTable` in hugo.toml
```toml
[markup.highlight]
lineNos = true
lineNumbersInTable = true
```
2. create a syntax highlighting code block with long enough content 

### Observed Results:

-   What happened?
<img width="1113" alt="longlineoverflow" src="https://github.com/luizdepra/hugo-coder/assets/87026494/2f241472-dfce-482c-beab-2ef7d92f1a2a">

if I turn the `lineNumbersInTable` to false, the overflowed part will be hidden.

<img width="1113" alt="longlineoverflow_disable_linenumbersintable" src="https://github.com/luizdepra/hugo-coder/assets/87026494/174b1a8e-1d8d-4868-b8a6-5b4b519c6908">

-   What did you expect to happen?

The code block should hide the overflowed element, and able to be scrolled horizontally to view the content.
<img width="1113" alt="longlineoverflow_scroll" src="https://github.com/luizdepra/hugo-coder/assets/87026494/21eae278-d7ca-4a51-9d2c-fcaf07f574fe">

I added a workaround to `_base.scss`, to get my expecting result
```scss
.highlight {
  div,
  pre {
    margin: 2rem 0 2rem;
    padding: 1rem;
    border-radius: 1rem;
    overflow: auto; // <- add this
  }
}
```

I'm not sure if it will cause any breaking changes, or anywhere else needed to be updated in order to fix it, so open a issue. Thanks for helping.

### Relevant code exceptions or logs

N/A
